// ════════════════════════════════════════════════════════════════════════════
// PLANET DOSSIER DATA
// Cinematic per-world briefing content: title card, data sheet, orbiting
// hotspot ring, and interior cutaway layers.
//
// Figures follow the NASA Planetary Fact Sheet (nssdc.gsfc.nasa.gov).
// Layer `outer` values are a fraction of the body radius (1 = surface, 0 = centre)
// and drive the real 3D cutaway geometry, so they must stay ordered largest→smallest.
// ════════════════════════════════════════════════════════════════════════════

export const DOSSIERS = {
  // ─── SUN ──────────────────────────────────────────────────────────────────
  sun: {
    name: 'Sun',
    classification: 'G2V Main-sequence star',
    headline: '1.989 × 10³⁰ kg',
    headlineLabel: 'Mass',
    blurb: 'The gravitational anchor of the solar system, holding 99.86% of all its mass.',
    texture: '8k_sun.jpg',
    tint: 0xffffff,
    emissive: true,
    stats: {
      'Mass': '1.989 × 10³⁰ kg',
      'Diameter': '1,392,700 km',
      'Density': '1,408 kg/m³',
      'Surface gravity': '274 m/s²',
      'Escape velocity': '617.7 km/s',
      'Rotation period': '25.4 days',
      'Surface temperature': '5,505 °C',
      'Core temperature': '15,000,000 °C',
      'Age': '4.6 billion years'
    },
    hotspots: [
      { title: 'Core Fusion', text: 'Every second, 600 million tonnes of hydrogen fuse into helium, converting 4 million tonnes of matter directly into energy.' },
      { title: 'Radiative Zone', text: 'Photons random-walk outward through this dense region, taking up to 170,000 years to cross a distance light would clear in two seconds.' },
      { title: 'Convective Zone', text: 'Plasma boils in colossal cells, carrying heat to the surface and painting the photosphere with a granular texture.' },
      { title: 'Photosphere', text: 'The visible surface, a 500 km shell of plasma at 5,505 °C where sunlight finally escapes into space.' },
      { title: 'Sunspots', text: 'Cooler magnetic bruises, some wider than Earth, that track an 11-year cycle of rising and falling solar activity.' },
      { title: 'Solar Corona', text: 'The outer atmosphere burns at over a million degrees, hundreds of times hotter than the surface beneath it.' },
      { title: 'Solar Wind', text: 'A continuous stream of charged particles races outward at 400 km/s, shaping every magnetosphere it meets.' },
      { title: 'Heliosphere', text: 'The Sun\'s magnetic bubble extends far beyond Neptune, defining the true edge of the solar system.' }
    ],
    layers: [
      { name: 'Corona', outer: 1.00, color: 0xffb066, detail: 'Over 1,000,000 °C' },
      { name: 'Photosphere', outer: 0.86, color: 0xffd489, detail: '5,505 °C · 500 km' },
      { name: 'Convective zone', outer: 0.80, color: 0xff9b3d, detail: '200,000 km' },
      { name: 'Radiative zone', outer: 0.50, color: 0xff6b1f, detail: '300,000 km' },
      { name: 'Core', outer: 0.25, color: 0xfff3c4, detail: '15,000,000 °C' }
    ]
  },

  // ─── MERCURY ──────────────────────────────────────────────────────────────
  mercury: {
    name: 'Mercury',
    classification: 'Terrestrial planet · I',
    headline: '3.301 × 10²³ kg',
    headlineLabel: 'Mass',
    blurb: 'The smallest planet and the fastest, completing a full orbit in just 88 days.',
    texture: '8k_mercury.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '3.301 × 10²³ kg',
      'Diameter': '4,879 km',
      'Density': '5,429 kg/m³',
      'Surface gravity': '3.7 m/s²',
      'Escape velocity': '4.3 km/s',
      'Rotation period': '1,407.6 hours',
      'Orbital period': '88 days',
      'Axial tilt': '0.034°',
      'Moons': 'None'
    },
    hotspots: [
      { title: 'Planet History', text: 'Formed 4.5 billion years ago, Mercury may have lost most of its rocky mantle in a colossal early impact, leaving an outsized core.' },
      { title: 'No Atmosphere', text: 'Only a wisp of an exosphere survives, atoms blasted loose from the surface by the solar wind and micrometeorites.' },
      { title: 'Temperature Extremes', text: 'Without air to hold heat, the surface swings from 430 °C in daylight to −180 °C at night.' },
      { title: 'Planet Layers', text: 'An enormous iron core fills roughly 85% of the planet\'s radius, the largest core-to-body ratio in the solar system.' },
      { title: 'Magnetic Field', text: 'A weak but genuine global field, about 1% of Earth\'s strength, generated by a still-molten outer core.' },
      { title: 'Caloris Basin', text: 'A 1,550 km impact crater so violent that the shock waves buckled terrain on the exact opposite side of the planet.' },
      { title: 'Polar Ice', text: 'Craters at the poles never see sunlight and hold water ice, on the planet closest to the Sun.' },
      { title: 'Orbital Resonance', text: 'Mercury rotates three times for every two orbits, so a single solar day lasts two Mercurian years.' }
    ],
    layers: [
      { name: 'Crust', outer: 1.00, color: 0x9c8f7a, detail: '35 km' },
      { name: 'Mantle', outer: 0.986, color: 0x6f6354, detail: '420 km' },
      { name: 'Outer core', outer: 0.814, color: 0xd98b4a, detail: '490 km' },
      { name: 'Inner core', outer: 0.613, color: 0xffd9a0, detail: '1,530 km radius' }
    ]
  },

  // ─── VENUS ────────────────────────────────────────────────────────────────
  venus: {
    name: 'Venus',
    classification: 'Terrestrial planet · II',
    headline: '4.867 × 10²⁴ kg',
    headlineLabel: 'Mass',
    blurb: 'Earth\'s twin in size, transformed by a runaway greenhouse into the hottest world we know.',
    texture: '8k_venus_surface.jpg',
    tint: 0xffe6b8,
    stats: {
      'Mass': '4.867 × 10²⁴ kg',
      'Diameter': '12,104 km',
      'Density': '5,243 kg/m³',
      'Surface gravity': '8.87 m/s²',
      'Escape velocity': '10.36 km/s',
      'Rotation period': '−5,832.5 hours',
      'Orbital period': '224.7 days',
      'Surface pressure': '92 bar',
      'Moons': 'None'
    },
    hotspots: [
      { title: 'Planet History', text: 'Venus may have held shallow oceans for two billion years before rising solar output boiled them into the sky.' },
      { title: 'Atmosphere', text: 'A crushing blanket of 96% carbon dioxide presses down at 92 times Earth\'s sea-level pressure.' },
      { title: 'Runaway Greenhouse', text: 'Trapped infrared radiation holds the surface at a uniform 465 °C, hot enough to melt lead, day or night.' },
      { title: 'Sulphuric Clouds', text: 'Decks of sulphuric acid cloud circle the planet in just four days, sixty times faster than the ground below.' },
      { title: 'Planet Layers', text: 'A thin basaltic crust over a silicate mantle and an iron core that appears to generate no global magnetic field.' },
      { title: 'Volcanism', text: 'More than 1,600 major volcanoes mark a surface repaved by eruptions within the last 500 million years.' },
      { title: 'Retrograde Spin', text: 'Venus turns backwards and slower than it orbits, so its day is longer than its year.' },
      { title: 'Surface Mapping', text: 'Radar from the Magellan orbiter pierced the clouds to reveal continents, rifts and lava plains beneath.' }
    ],
    layers: [
      { name: 'Crust', outer: 1.00, color: 0xc9a86a, detail: '20 km' },
      { name: 'Mantle', outer: 0.997, color: 0x8a6b3d, detail: '2,800 km' },
      { name: 'Core', outer: 0.534, color: 0xffc48a, detail: '3,200 km radius' }
    ]
  },

  // ─── EARTH ────────────────────────────────────────────────────────────────
  earth: {
    name: 'Earth',
    classification: 'Terrestrial planet · III',
    headline: '5.972 × 10²⁴ kg',
    headlineLabel: 'Mass',
    blurb: 'The only world known to carry life, wrapped in liquid water and a breathable sky.',
    texture: '8k_earth_daymap.jpg',
    nightTexture: '8k_earth_nightmap.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '5.972 × 10²⁴ kg',
      'Diameter': '12,756 km',
      'Density': '5,514 kg/m³',
      'Surface gravity': '9.807 m/s²',
      'Escape velocity': '11.19 km/s',
      'Rotation period': '23.93 hours',
      'Orbital period': '365.25 days',
      'Axial tilt': '23.44°',
      'Moons': '1 · Luna'
    },
    hotspots: [
      { title: 'Planet History', text: 'Assembled 4.54 billion years ago from the solar nebula, then struck by a Mars-sized body that cast off the Moon.' },
      { title: 'Atmosphere', text: 'Seventy-eight percent nitrogen and twenty-one percent oxygen, an ozone layer above absorbing the ultraviolet that would sterilise the surface.' },
      { title: 'Oceans', text: 'Liquid water covers 71% of the planet and holds 97% of its water, driving heat around the globe in vast currents.' },
      { title: 'Planet Layers', text: 'A thin crust floats on a convecting mantle above a liquid outer core and a solid iron inner core.' },
      { title: 'Magnetic Field', text: 'Currents in the molten outer core generate a magnetosphere that deflects the solar wind and shields the biosphere.' },
      { title: 'Weather', text: 'Uneven solar heating and rotation spin the atmosphere into jet streams, cyclones and a restless global climate.' },
      { title: 'Life on Earth', text: 'Life appeared at least 3.7 billion years ago and now spans an estimated 8.7 million species.' },
      { title: 'Earth\'s Moon', text: 'Luna stabilises the axial tilt that keeps the seasons regular, and raises the tides twice a day.' }
    ],
    layers: [
      { name: 'Crust', outer: 1.00, color: 0x4a7c59, detail: '5 – 70 km' },
      { name: 'Mantle', outer: 0.9945, color: 0xb2542a, detail: '2,890 km' },
      { name: 'Outer core', outer: 0.546, color: 0xff9c3d, detail: '2,260 km · liquid' },
      { name: 'Inner core', outer: 0.191, color: 0xfff0b8, detail: '1,220 km radius · solid' }
    ]
  },

  // ─── MOON ─────────────────────────────────────────────────────────────────
  moon: {
    name: 'Moon',
    classification: 'Natural satellite of Earth',
    headline: '7.346 × 10²² kg',
    headlineLabel: 'Mass',
    blurb: 'Earth\'s single companion, locked in synchronous rotation and always facing us.',
    texture: '8k_moon.jpg',
    tint: 0xd8d5cc,
    stats: {
      'Mass': '7.346 × 10²² kg',
      'Diameter': '3,475 km',
      'Density': '3,340 kg/m³',
      'Surface gravity': '1.62 m/s²',
      'Escape velocity': '2.38 km/s',
      'Rotation period': '655.7 hours',
      'Distance from Earth': '384,400 km',
      'Orbital period': '27.3 days',
      'Temperature': '−173 to 127 °C'
    },
    hotspots: [
      { title: 'Formation', text: 'Born from the debris of a giant impact between the young Earth and a Mars-sized protoplanet called Theia.' },
      { title: 'Maria', text: 'The dark plains are ancient basaltic floods that filled enormous impact basins over three billion years ago.' },
      { title: 'Highlands', text: 'Bright, heavily cratered terrain made of anorthosite, the oldest surviving crust in the Earth-Moon system.' },
      { title: 'Regolith', text: 'A layer of pulverised dust and rock metres deep, ground down by billions of years of micrometeorite impacts.' },
      { title: 'Tidal Locking', text: 'The Moon rotates exactly once per orbit, so the same hemisphere has faced Earth for billions of years.' },
      { title: 'Tides', text: 'Lunar gravity raises two tidal bulges in Earth\'s oceans and is slowly lengthening our day.' },
      { title: 'Water Ice', text: 'Permanently shadowed polar craters hold billions of tonnes of water ice, a resource for future crews.' },
      { title: 'Apollo Landings', text: 'Twelve people walked here between 1969 and 1972, returning 382 kilograms of rock and soil.' }
    ],
    layers: [
      { name: 'Crust', outer: 1.00, color: 0xbdb8ad, detail: '~50 km' },
      { name: 'Mantle', outer: 0.971, color: 0x6e6a62, detail: '1,300 km' },
      { name: 'Outer core', outer: 0.28, color: 0xd9a05a, detail: '~90 km · liquid' },
      { name: 'Inner core', outer: 0.176, color: 0xffe0a8, detail: '~240 km radius' }
    ]
  },

  // ─── MARS ─────────────────────────────────────────────────────────────────
  mars: {
    name: 'Mars',
    classification: 'Terrestrial planet · IV',
    headline: '6.417 × 10²³ kg',
    headlineLabel: 'Mass',
    blurb: 'A cold desert world of rust and ice that once ran with rivers and standing water.',
    texture: '8k_mars.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '6.417 × 10²³ kg',
      'Diameter': '6,792 km',
      'Density': '3,934 kg/m³',
      'Surface gravity': '3.71 m/s²',
      'Escape velocity': '5.03 km/s',
      'Rotation period': '24.62 hours',
      'Orbital period': '687 days',
      'Axial tilt': '25.19°',
      'Moons': '2 · Phobos, Deimos'
    },
    hotspots: [
      { title: 'Planet History', text: 'Warm and wet for its first billion years, Mars lost its magnetic field and then its atmosphere to the solar wind.' },
      { title: 'Atmosphere', text: 'A thin skin of carbon dioxide at less than 1% of Earth\'s pressure, too sparse to hold warmth.' },
      { title: 'Ancient Water', text: 'Dry river valleys, deltas and lake beds record billions of years of flowing surface water.' },
      { title: 'Planet Layers', text: 'A basaltic crust over a silicate mantle and a surprisingly large, low-density liquid core.' },
      { title: 'Olympus Mons', text: 'The tallest volcano in the solar system rises 22 km, nearly three times the height of Everest.' },
      { title: 'Valles Marineris', text: 'A canyon system 4,000 km long and 7 km deep, long enough to span the United States.' },
      { title: 'Polar Caps', text: 'Layered water and carbon dioxide ice that grow and retreat with the Martian seasons.' },
      { title: 'Dust Storms', text: 'Regional storms can escalate into global events that shroud the entire planet for months.' }
    ],
    layers: [
      { name: 'Crust', outer: 1.00, color: 0xc1653a, detail: '~50 km' },
      { name: 'Mantle', outer: 0.985, color: 0x7a3f26, detail: '1,550 km' },
      { name: 'Core', outer: 0.539, color: 0xffab6b, detail: '1,830 km radius · liquid' }
    ]
  },

  // ─── JUPITER ──────────────────────────────────────────────────────────────
  jupiter: {
    name: 'Jupiter',
    classification: 'Gas giant · V',
    headline: '1.898 × 10²⁷ kg',
    headlineLabel: 'Mass',
    blurb: 'A world so massive that every other planet could fit inside it twice over.',
    texture: '8k_jupiter.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '1.898 × 10²⁷ kg',
      'Diameter': '142,984 km',
      'Density': '1,326 kg/m³',
      'Surface gravity': '24.79 m/s²',
      'Escape velocity': '59.5 km/s',
      'Rotation period': '9.93 hours',
      'Orbital period': '11.86 years',
      'Cloud temperature': '−110 °C',
      'Moons': '95 known'
    },
    hotspots: [
      { title: 'Planet History', text: 'The first planet to form, Jupiter gathered so much of the early nebula that it shaped every orbit that followed.' },
      { title: 'Atmosphere', text: 'Ninety percent hydrogen and ten percent helium, banded into alternating jets of rising and sinking cloud.' },
      { title: 'Great Red Spot', text: 'An anticyclone wider than Earth that has been turning for at least 350 years, though it is slowly shrinking.' },
      { title: 'Planet Layers', text: 'No solid surface: gas thickens into liquid, then into metallic hydrogen, around a diffuse heavy core.' },
      { title: 'Magnetic Field', text: 'The strongest planetary magnetosphere in the solar system, 20,000 times Earth\'s and larger than the Sun on our sky.' },
      { title: 'Galilean Moons', text: 'Io, Europa, Ganymede and Callisto, spotted by Galileo in 1610 and proof that not everything orbits Earth.' },
      { title: 'Europa\'s Ocean', text: 'Beneath a shell of ice lies a salt-water ocean holding perhaps twice the water of all Earth\'s seas.' },
      { title: 'Ring System', text: 'A faint dusty ring, discovered by Voyager 1, fed by material blasted off the inner moons.' }
    ],
    layers: [
      { name: 'Upper atmosphere', outer: 1.00, color: 0xd9b98a, detail: 'Ammonia clouds' },
      { name: 'Molecular hydrogen', outer: 0.94, color: 0xb98d5e, detail: '~20,000 km' },
      { name: 'Metallic hydrogen', outer: 0.72, color: 0x8a6bb0, detail: '~45,000 km' },
      { name: 'Core', outer: 0.20, color: 0xfff0c4, detail: '~20,000 km · diffuse' }
    ]
  },

  // ─── SATURN ───────────────────────────────────────────────────────────────
  saturn: {
    name: 'Saturn',
    classification: 'Gas giant · VI',
    headline: '5.683 × 10²⁶ kg',
    headlineLabel: 'Mass',
    blurb: 'The ringed giant, less dense than water and circled by billions of icy fragments.',
    texture: '8k_saturn.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '5.683 × 10²⁶ kg',
      'Diameter': '120,536 km',
      'Density': '687 kg/m³',
      'Surface gravity': '10.44 m/s²',
      'Escape velocity': '35.5 km/s',
      'Rotation period': '10.66 hours',
      'Orbital period': '29.45 years',
      'Axial tilt': '26.73°',
      'Moons': '146 known'
    },
    hotspots: [
      { title: 'Planet History', text: 'Formed beyond the frost line 4.5 billion years ago, capturing a vast envelope of hydrogen and helium.' },
      { title: 'Ring System', text: 'Spanning 280,000 km but often under 10 metres thick, made of ice and rock from pebbles to houses.' },
      { title: 'Atmosphere', text: 'Banded hydrogen and helium with winds reaching 1,800 km/h near the equator.' },
      { title: 'Planet Layers', text: 'A hydrogen envelope compressing into metallic hydrogen around a dense rock and ice core.' },
      { title: 'Hexagon Storm', text: 'A persistent six-sided jet stream at the north pole, each side longer than the diameter of Earth.' },
      { title: 'Lowest Density', text: 'At 687 kg/m³ Saturn is the only planet that would float, given an ocean large enough to hold it.' },
      { title: 'Titan', text: 'The one moon with a thick atmosphere, where rivers and lakes of liquid methane carve the surface.' },
      { title: 'Enceladus', text: 'Geysers erupt from a subsurface ocean through fractures at the south pole, feeding Saturn\'s E ring.' }
    ],
    layers: [
      { name: 'Upper atmosphere', outer: 1.00, color: 0xe3cfa0, detail: 'Ammonia haze' },
      { name: 'Molecular hydrogen', outer: 0.93, color: 0xc2a06d, detail: '~30,000 km' },
      { name: 'Metallic hydrogen', outer: 0.60, color: 0x9178b5, detail: '~14,500 km' },
      { name: 'Core', outer: 0.25, color: 0xfff0c4, detail: 'Rock & ice' }
    ]
  },

  // ─── URANUS ───────────────────────────────────────────────────────────────
  uranus: {
    name: 'Uranus',
    classification: 'Ice giant · VII',
    headline: '8.681 × 10²⁵ kg',
    headlineLabel: 'Mass',
    blurb: 'An ice giant knocked onto its side, orbiting the Sun like a rolling ball.',
    texture: '2k_uranus.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '8.681 × 10²⁵ kg',
      'Diameter': '51,118 km',
      'Density': '1,270 kg/m³',
      'Surface gravity': '8.87 m/s²',
      'Escape velocity': '21.3 km/s',
      'Rotation period': '−17.24 hours',
      'Orbital period': '84 years',
      'Axial tilt': '97.77°',
      'Moons': '28 known'
    },
    hotspots: [
      { title: 'Planet History', text: 'A catastrophic early collision is the leading explanation for the near-perpendicular tilt of its axis.' },
      { title: 'Extreme Tilt', text: 'Tipped 98 degrees, each pole spends 42 years in continuous sunlight and then 42 years in darkness.' },
      { title: 'Atmosphere', text: 'Hydrogen and helium with methane that absorbs red light, giving the planet its pale cyan cast.' },
      { title: 'Planet Layers', text: 'A hydrogen envelope over a hot, dense fluid of water, methane and ammonia around a rocky core.' },
      { title: 'Coldest Planet', text: 'Cloud tops reach −224 °C, the lowest temperature measured anywhere in the solar system.' },
      { title: 'Magnetic Field', text: 'Tilted 59 degrees from the rotation axis and offset from the centre, producing a chaotic magnetosphere.' },
      { title: 'Ring System', text: 'Thirteen narrow, dark rings discovered in 1977 when the planet passed in front of a star.' },
      { title: 'Voyager 2', text: 'Still the only spacecraft to visit, passing within 81,500 km in January 1986.' }
    ],
    layers: [
      { name: 'Atmosphere', outer: 1.00, color: 0x9fd8e8, detail: 'H₂, He, CH₄' },
      { name: 'Mantle', outer: 0.88, color: 0x3f8fa8, detail: 'Water, methane & ammonia ice' },
      { name: 'Core', outer: 0.30, color: 0xd9c9a0, detail: 'Rock & iron' }
    ]
  },

  // ─── NEPTUNE ──────────────────────────────────────────────────────────────
  neptune: {
    name: 'Neptune',
    classification: 'Ice giant · VIII',
    headline: '1.024 × 10²⁶ kg',
    headlineLabel: 'Mass',
    blurb: 'The outermost planet, where the fastest winds in the solar system tear through the clouds.',
    texture: '2k_neptune.jpg',
    tint: 0xffffff,
    stats: {
      'Mass': '1.024 × 10²⁶ kg',
      'Diameter': '49,528 km',
      'Density': '1,638 kg/m³',
      'Surface gravity': '11.15 m/s²',
      'Escape velocity': '23.5 km/s',
      'Rotation period': '16.11 hours',
      'Orbital period': '164.8 years',
      'Axial tilt': '28.32°',
      'Moons': '16 known'
    },
    hotspots: [
      { title: 'Planet History', text: 'Likely formed closer to the Sun and migrated outward, scattering the icy bodies of the Kuiper Belt.' },
      { title: 'Discovery by Maths', text: 'Found in 1846 exactly where calculations of Uranus\'s wobble predicted it would be.' },
      { title: 'Atmosphere', text: 'Hydrogen, helium and methane, with the methane giving the planet its deep blue colour.' },
      { title: 'Supersonic Winds', text: 'Gusts reach 2,100 km/h, the fastest measured on any planet in the solar system.' },
      { title: 'Planet Layers', text: 'A gaseous envelope over a hot fluid mantle of water and ammonia ices around a rocky core.' },
      { title: 'Great Dark Spot', text: 'Voyager 2 photographed an Earth-sized storm in 1989 that had vanished when Hubble looked again.' },
      { title: 'Internal Heat', text: 'Neptune radiates 2.6 times more energy than it receives from the distant Sun.' },
      { title: 'Triton', text: 'A captured Kuiper Belt object orbiting backwards, with nitrogen geysers erupting from its frozen surface.' }
    ],
    layers: [
      { name: 'Atmosphere', outer: 1.00, color: 0x6ba8e8, detail: 'H₂, He, CH₄' },
      { name: 'Mantle', outer: 0.86, color: 0x2a5fa8, detail: 'Water & ammonia ices' },
      { name: 'Core', outer: 0.32, color: 0xd9c9a0, detail: 'Rock & iron' }
    ]
  }
};

/** Resolve a dossier for a mesh's userData id or name. */
export function getDossier(idOrName) {
  if (!idOrName) return null;
  const key = String(idOrName).toLowerCase();
  return DOSSIERS[key] || null;
}
